### ISSUE TITLE
can I use the gene data from Genomic cytometry website as the reference file?

### ISSUE THREAD

**Issue by YunZheHuang** [BatadaLab/scID#2]
Hello, 
Thank you so much for developing this tool. I just begin to use this tool in my research. I'm currently using Seurat to draw the clusters of my sample, now I want to identify the cell type of my sample. My PI recommended me using the data from Genomic Cytometry. However, the format of the file from Genomic cytometry is gtm format. I just wondering if I can use this file as the reference file in scID? Thank you !

**Comment by kboufea** [comment]
Hi, I assume the data you are downloading from Genomic Cytometry is the list unregulated genes per cell type. I have added a new function "gmt_to_markers" that accepts a .gmt file and converts it to a markers data frame you can use instead of a reference scRNAseq dataset. I hope this helps. Let me know if you have further questions.
